### ISSUE TITLE
Hit Tab button at last line will throw error

### ISSUE THREAD

**Issue by pnhuyduy** [muhimasri/b-editable-table#13]
When I focus at last input in last line and hit tab button, like this
![image](https://user-images.githubusercontent.com/46210597/144392115-59f07330-acee-45b1-b446-ba9815589e94.png)

Console log
![image](https://user-images.githubusercontent.com/46210597/144392317-49bedcae-3179-418d-9e64-6fd954c43e2d.png)
![image](https://user-images.githubusercontent.com/46210597/144392624-45b9026a-7520-4acd-8f26-909885532317.png)

Seem like you forgot to check `rowIndex` exists.

**Comment by muhimasri** [comment]
Thank you for creating an issue. I'll add a fix for this in the next release next week.

Cheers!

**Comment by Yet-Another-Programmer** [comment]
The [sandbox ](https://codesandbox.io/s/bootstrap-vue-editable-table-wx012?file=/src/App.vue) still contains the issue:
![grafik](https://user-images.githubusercontent.com/72605853/148053231-2941dfb0-5356-468f-862a-f05ce53bc329.png)

**Comment by muhimasri** [comment]
Thanks for the note. It should be fixed now. I published latest version and updated [CodeSandbox](https://codesandbox.io/s/bootstrap-vue-editable-table-wx012?file=/src/App.vue) example.

**Comment by Yet-Another-Programmer** [comment]
Works! No more error messages:
![grafik](https://user-images.githubusercontent.com/72605853/148087207-7e428ac3-1ce4-4c8c-87df-01ca4afa9891.png)
