### ISSUE TITLE
Date Field Design

### ISSUE THREAD

**Issue by AshutoshJha15** [muhimasri/b-editable-table#32]
![image](https://user-images.githubusercontent.com/50516423/197948567-d33619af-5f99-401b-8c4b-be81f66e908e.png)

My date field is not displaying properly

`<template>
  <div class="table-container">
    <b-editable-table bordered class="editable-table" v-model="items" :fields="fields" @input-change="handleInput"
                      :editMode="'cell'" :busy="loading">

      <template v-for="field in fields" v-slot:[createCell(field)]="data" >
        <div class="d-flex flex-column">
          <div>
          <span >
            {{ getCellData(field, data) }}
          </span>
          </div>
          <div v-if="getErrorsForCell(field,data) != null">
            <div :data-title="getErrorsForCell(field,data)" class="text-danger">
              {{ getErrorsForCell(field,data) | truncate(13) }}
            </div>
          </div>
        </div>
      </template>
      <template #table-busy>
        <div class="">
          <b-spinner style="width: 6rem; height: 6rem;" variant="primary" label="Spinning"></b-spinner>
        </div>
      </template>
    </b-editable-table>
  </div>
</template>
`

**Comment by muhimasri** [comment]
Hey there,

It seems like it's hidden behind the parent container. Are you able to increase the height of the parent container? Could you please provide me with the full html? The example in Codesandbox works well so it's hard to reproduce https://codesandbox.io/s/bootstrap-vue-editable-table-wx012?file=/src/App.vue

**Comment by AshutoshJha15** [comment]
If I increase the height of the container it is working but the layout of the calender does not look right
![image](https://user-images.githubusercontent.com/50516423/198197573-915311e0-e675-4204-8cfd-c48f331eba8b.png)

**Comment by AshutoshJha15** [comment]
<template>
  <div>
    <b-editable-table bordered class="editable-table" v-model="items" :fields="fields" @input-change="handleInput"
                      :editMode="'cell'" :busy="loading">

      <template v-for="field in fields" v-slot:[createCell(field)]="data">
        <div class="d-flex flex-column">
          <div>
          <span>
            {{ getCellData(field, data) }}
          </span>
          </div>
          <div v-if="getErrorsForCell(field,data) != null">
            <div :data-title="getErrorsForCell(field,data)" class="text-danger">
              {{ getErrorsForCell(field, data) | truncate(25) }}
            </div>
          </div>
        </div>
      </template>
      <template #table-busy>
        <div class="">
          <b-spinner style="width: 6rem; height: 6rem;" variant="primary" label="Spinning"></b-spinner>
        </div>
      </template>
    </b-editable-table>
  </div>
</template>


<script>
import BEditableTable from 'bootstrap-vue-editable-table';
import {BSpinner} from 'bootstrap-vue';


export default {
  name: "HrEndorsement",
  components: {
    BEditableTable,
    BSpinner
  },
  data() {
    return {
      fields: [
        {
          key: "employee_code",
          label: "Employee Code",
          type: "text",
          editable: true,
          placeholder: "Enter Employee code",
          class: "name-col",
        },
        {
          key: "name",
          label: "Name",
          type: "text",
          editable: true,
          placeholder: "Enter Name...",
          class: "name-col",
          required: true
        },
        {
          key: "birthdate",
          label: "Birthdate",
          type: "date",
          editable: true,
          placeholder: "Enter Birthdate...",
          class: "name-col date",
          required: true
        },
        {
          key: "mobile_number",
          label: "Mobile Number",
          type: "text",
          editable: true,
          placeholder: "Enter Mobile Number...",
          class: "name-col"
        },
        {
          key: "gender", label: "Gender", type: "select", editable: true, class: "department-col", options: [
            {value: 'Male', text: 'Male'},
            {value: 'Female', text: 'Female'},
            {value: 'Other', text: 'Other'},
          ]
        },
        {key: "email", label: "Email", type: "email", editable: true, placeholder: "Enter Email", class: "age-col"},
        {
          key: "joining_date",
          label: "Joining Date",
          type: "text",
          editable: true,
          placeholder: "Enter Joining Date",
          class: "joining_date"
        },
        {
          key: "family_composition",
          label: "Family Composition",
          type: "text",
          editable: false,
          placeholder: "Enter Family Composition",
          class: "age-col"
        },
        {key: "sum_insured", label: "Sum Insured", type: "text", editable: false, class: "age-col"},
        {
          key: "partner_name",
          label: "Partner name",
          type: "text",
          editable: true,
          placeholder: "Enter Partner name",
          class: "age-col"
        },
        {
          key: "partner_email",
          label: "Partner email",
          type: "email",
          editable: true,
          placeholder: "Enter Partner email",
          class: "age-col"
        },
        {
          key: "partner_mobile",
          label: "Partner mobile",
          type: "text",
          editable: true,
          placeholder: "Enter Partner mobile",
          class: "age-col"
        },
        {
          key: "partner_gender",
          label: "Partner Gender",
          type: "select",
          editable: true,
          class: "department-col",
          options: [
            {value: 'Male', text: 'Male'},
            {value: 'Female', text: 'Female'},
            {value: 'Other', text: 'Other'},
          ]
        },
        {
          key: "partner_birthdate",
          label: "Partner birthdate",
          type: "text",
          editable: true,
          placeholder: "Enter Partner birthdate",
          class: "age-col"
        },
        {
          key: "child_1_name",
          label: "Enter Child 1 name",
          type: "text",
          editable: true,
          placeholder: "Enter Child 1 name",
          class: "age-col"
        },
        {
          key: "child_1_birthdate",
          label: "Enter Child 1 birthdate",
          type: "text",
          editable: true,
          placeholder: "Enter Child 1 birthdate",
          class: "age-col"
        },
        {
          key: "child_1_gender",
          label: "Enter Child 1 gender",
          type: "select",
          editable: true,
          class: "department-col",
          options: [
            {value: 'Male', text: 'Male'},
            {value: 'Female', text: 'Female'},
            {value: 'Other', text: 'Other'},
          ]
        },
        {
          key: "child_2_name",
          label: "Enter Child 1 name",
          type: "text",
          editable: true,
          placeholder: "Enter Child 2 name",
          class: "age-col"
        },
        {
          key: "child_2_birthdate",
          label: "Enter Child 2 birthdate",
          type: "text",
          editable: true,
          placeholder: "Enter Child 2 birthdate",
          class: "age-col"
        },
        {
          key: "child_2_gender",
          label: "Enter Child 2 gender",
          type: "select",
          editable: true,
          class: "department-col",
          options: [
            {value: 'Male', text: 'Male'},
            {value: 'Female', text: 'Female'},
            {value: 'Other', text: 'Other'},
          ]
        },
        {
          key: "child_3_name",
          label: "Enter Child 3 name",
          type: "text",
          editable: true,
          placeholder: "Enter Child 3 name",
          class: "age-col"
        },
        {
          key: "child_3_birthdate",
          label: "Enter Child 3 birthdate",
          type: "text",
          editable: true,
          placeholder: "Enter Child 3 birthdate",
          class: "age-col"
        },
        {
          key: "child_3_gender",
          label: "Enter Child 3 gender",
          type: "select",
          editable: true,
          class: "department-col",
          options: [
            {value: 'Male', text: 'Male'},
            {value: 'Female', text: 'Female'},
            {value: 'Other', text: 'Other'},
          ]
        },
        {
          key: "child_4_name",
          label: "Enter Child 4 name",
          type: "text",
          editable: true,
          placeholder: "Enter Child 1 name",
          class: "age-col"
        },
        {
          key: "child_4_birthdate",
          label: "Enter Child 4 birthdate",
          type: "text",
          editable: true,
          placeholder: "Enter Child 1 birthdate",
          class: "age-col"
        },
        {
          key: "child_4_gender",
          label: "Enter Child 4 gender",
          type: "select",
          editable: true,
          class: "department-col",
          options: [
            {value: 'Male', text: 'Male'},
            {value: 'Female', text: 'Female'},
            {value: 'Other', text: 'Other'},
          ]
        },
        {
          key: "fil_name",
          label: "Father in law name",
          type: "text",
          editable: true,
          placeholder: "Enter Partner name",
          class: "age-col"
        },
        {
          key: "fil_email",
          label: "Father in law email",
          type: "email",
          editable: true,
          placeholder: "Enter Partner email",
          class: "age-col"
        },
        {
          key: "fil_mobile",
          label: "Father in law mobile",
          type: "text",
          editable: true,
          placeholder: "Enter Partner mobile",
          class: "age-col"
        },
        {
          key: "fil_birthdate",
          label: "Father in law birthdate",
          type: "text",
          editable: true,
          placeholder: "Enter Partner birthdate",
          class: "age-col"
        },
        {
          key: "mil_name",
          label: "Mother in law name",
          type: "text",
          editable: true,
          placeholder: "Enter Partner name",
          class: "age-col"
        },
        {
          key: "mil_email",
          label: "Mother in law email",
          type: "email",
          editable: true,
          placeholder: "Enter Partner email",
          class: "age-col"
        },
        {
          key: "mil_mobile",
          label: "Mother in law mobile",
          type: "text",
          editable: true,
          placeholder: "Enter Partner mobile",
          class: "age-col"
        },
        {
          key: "mil_birthdate",
          label: "Mother in law birthdate",
          type: "text",
          editable: true,
          placeholder: "Enter Partner birthdate",
          class: "age-col"
        },

      ],
      items: [],
      loading: true,
    };
  },
  filters: {
    truncate: function (data, num) {
      if (data == null) {
        return null;
      }
      return data.split("").slice(0, num).join("") + '...';
    }
  },
  methods: {
    handleInput(value) {
      this.loading = true;
      let record = value;
      record.item[record.field.key] = record.value;
      axios.post('/hr/endorsements/update-data', {
        record: record,
      }).then((response) => {
        this.items[value.index] = response.data;
        this.$set(this.items, value.index, response.data)

        console.log(this.items[value.index]);
        this.loading = false;
      }).catch(function (error) {
        console.log(error);
      });
    },
    createCell(key) {
      return `cell(${key.key})`;
    },
    getCellData(key, data) {
      return data.item[key.key];
    },

    getErrorsForCell(key, data) {
      if (data.item.errors[key.key] === undefined) {
        return null;
      }
      return data.item.errors[key.key][0];
    },

  },

  mounted() {
    this.loading = true;
    axios.get('/hr/endorsements/get-data')
        .then((response) => {
          this.items = response.data;
          this.loading = false;
          // handle success
          console.log(response);
        })
        .catch(function (error) {
          // handle error
          console.log(error);
        })
        .then(function () {
          // always executed
        });

  }
};
</script>

<style>
table {
  --bs-table-bg: #FFFFFF;
  --bs-table-accent-bg: transparent;
  --bs-table-striped-color: #181c32;
  --bs-table-striped-bg: rgba(245, 248, 250, 0.75);
  --bs-table-active-color: #181c32;
  --bs-table-active-bg: #f5f8fa;
  --bs-table-hover-color: #181c32;
  --bs-table-hover-bg: #f5f8fa;
  width: 100%;
  margin-bottom: 1rem;
  color: #181c32;
  vertical-align: top;
  border-color: #eff2f5;
}

thead {
  border-color: inherit;
  border-style: solid;
  border-width: 0;
}

table.editable-table th {
  min-width: 255px;
}

table.editable-table tr {
  border-bottom-width: 1px !important;
  border-bottom-style: dashed !important;
  border-bottom-color: #eff2f5 !important;
}

table.editable-table {
  margin: 0 !important;
  width: 100%;
}

table.editable-table td {
  /*padding-top: 1.25rem;*/
  /*padding-bottom: 1.25rem;*/
}

table.editable-table th {
  padding-top: 1.25rem;
  padding-bottom: 1.25rem;
}

.editable-table .data-cell {
  padding: 8px;
  vertical-align: middle;
}

.editable-table .custom-checkbox {
  width: 50px;
}

[data-title] {
  font-size: 13px;
  position: relative;
  cursor: help;
}

[data-title]:hover::before {
  content: attr(data-title);
  position: absolute;
  bottom: -46px;
  padding: 10px;
  background: red;
  color: #fff;
  font-size: 14px;
  white-space: nowrap;
}

[data-title]:hover::after {
  content: '';
  position: absolute;
  bottom: -12px;
  left: 8px;
  border: 8px solid transparent;
  border-bottom: 8px solid #000;
}

</style>

**Comment by AshutoshJha15** [comment]
Thanks for your support. I have figure it out

![image](https://user-images.githubusercontent.com/50516423/198209604-d48dabc3-b5a1-47ee-af7b-42cf2a8bcbca.png)

**Comment by AshutoshJha15** [comment]
One more help i need I want the date to be in dd/mm/yyyy  format how can I achieve this?

**Comment by muhimasri** [comment]
You can pass the field object any date prop available in BootstrapVue date picker. For example, the below code will format to "mm/dd/yyyy" :

```
{
          key: "dateOfBirth",
          label: "Date Of Birth",
          type: "date",
          editable: true,
          class: "date-col",
          locale: "en",
          "date-format-options": {
            year: "numeric",
            month: "numeric",
            day: "numeric",
          },
        },
}
```

You can look at the full API here https://bootstrap-vue.org/docs/components/form-datepicker#date-string-format
