### ISSUE TITLE
Handle keyup, blur event for input

### ISSUE THREAD

**Issue by yoursantu** [muhimasri/b-editable-table#34]
Hi,
Firstly i thankful for awesome component. 
i am building a custom stock inventory project using this component. 
i want to apply some predefined calculations for some column cells based on some value is entered in 
input fields on keyup or when tab or enter key is pressed the data should be updated.
currently it is working once value is entered and click outside of the table.  

Thank you.

**Comment by muhimasri** [comment]
You are very welcome! I'm glad you are using it in your project and yes values do update automatically as you press enter, tab or mouse out.

Please let me know if you suggest new improvements and features. Cheers :)

**Comment by yoursantu** [comment]
Hi,
Thank you very much for your reply,
And currently i have approached by using watch property. once the changes found in v-model, the watcher will watch the value changes and apply the required calculations on press enter, tab or mouse out event.
Is it possible to add @input event support for this component, if yes that could be more useful and will get updated values immediately oninput!!


Thank you, 
And Thank you very much for grate Component!!

**Comment by muhimasri** [comment]
Hello,

Yes there is @input-change event that is triggered whenever input values are changed. Please give it a try and let me know. Here is the link to the API:

https://b-editable-table.muhimasri.com/guide/api.html

Let mw know if that works.

Cheers!
