### ISSUE TITLE
Mask on edit fields

### ISSUE THREAD

**Issue by btls-treinamentos** [muhimasri/b-editable-table#35]
Hi. Thanks for this component, it's very helpful and I'm using in a project right now. I have a doubt..... I try to use some mask in the input field, but without success. is it possible to use mask on the input fields? I must use mask for currency values e percentual values in my inputs.

**Comment by muhimasri** [comment]
Hey there, you are very welcome!

Have you tried using the formatter from BootstrapVue input? You can pass any BootstrapVue input props in the field as follows:

```
{ formatter: this.formatter, key: "name", label: "Name", type: "text", editable: true, placeholder: "Enter Name...", class: "name-col"},
```

Then you can define your formatter function:

```
formatter(value) {
        return value.toLowerCase()
      }
```

Here is the BootstrapVue formatter documentation:

https://bootstrap-vue.org/docs/components/form-input#formatter-support
