### ISSUE TITLE
Is there any way to use textarea for bigger content

### ISSUE THREAD

**Issue by AshutoshJha15** [muhimasri/b-editable-table#36]

**Comment by muhimasri** [comment]
Currently there is no built in text area type but I'll add it in the next release.

For now, you can use custom cells to add your own element. Here is an example:

https://b-editable-table.muhimasri.com/guide/custom-cell.html

**Comment by muhimasri** [comment]
Please install latest v1.0.0. Textarea is now supported. `type: "textarea"`

https://b-editable-table.muhimasri.com/guide/form-elements.html
