### ISSUE TITLE
Please make style scoped

### ISSUE THREAD

**Issue by pavaniborra** [muhimasri/b-editable-table#42]
Please make style scoped. We are using b-table in our project, since the styles are not scoped, there is  global style leak in our project.

**Comment by muhimasri** [comment]
Thanks for bringing this up. I can see that you created a pull request for the scoped styling. I'll review, run tests and approve as soon as possible.

**Comment by muhimasri** [comment]
The scoped fix is now published to the latest version 1.0.4
